controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_0_joint
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: home
